# Generated by Django 3.2 on 2022-03-30 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Box',
        ),
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': 'Boxes'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
