# Generated by Django 3.2 on 2022-04-17 08:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0004_alter_box_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
