# Generated by Django 3.2 on 2022-04-16 08:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_default_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_postcode',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
